// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwfoumoaotswlzbzbcdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3Zm91bW9hb3Rzd2x6YnpiY2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzE4MzcsImV4cCI6MjA2NDU0NzgzN30.ZqyzwZMUU2Gz7noIUoqaIjNXqBmxn9HbUmwDV3Y2XF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);